{{- if .Values.ingress.enabled }}
{{- range $name, $route := .Values.ingress.routes }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}-{{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  entryPoints:
    - websecure
  {{- if $.Values.ingress.tls.enabled }}
  tls:
    certResolver: {{ $.Values.ingress.tls.certResolver }}
  {{- end }}
  routes:
  - match: Host(`{{ $route.host }}`)
    kind: Rule
    {{- if $.Values.ingress.middlewares }}
    middlewares:
    {{- range $.Values.ingress.middlewares }}
    - name: {{ . }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
    {{- end }}
    {{- end }}
    services:
    - name: {{ $.Release.Name }}-{{ $name }}
      port: {{ $route.port }}
{{- end }}
{{- end }}
